esphome:
  name: esp32-dfrobotshtc3

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Example configuration entry for ESP32
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

# Example configuration entry
sensor:
  - platform: shtcx
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    address: 0x70
    update_interval: 60s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rZav+t9UKlMJNJ8qIP4gFNctUPDMwxpd8/09kB/5ROs="

ota:
  password: "f52cf24253c8e69ced6e9170ebd6f018"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Dfrobotshtc3"
    password: "mj5TZcK5VclF"

captive_portal:
    